import { W } from '../data/words.js';
const have = new Set(W.map(w => w[0].toLowerCase()));

const OXFORD = {
  A1: ['apple','baby','bag','bath','bed','bike','bird','boat','book','box','boy','bread','car','cat','chair','child','city','class','cold','come','cook','cup','cut','dance','day','door','draw','dream','drink','drive','drop','dry','eat','eye','face','fall','farm','feel','fire','fish','fly','foot','friend','fun','game','garden','girl','give','glass','hand','head','heart','home','horse','hot','house','idea','jump','just','keep','kid','know','large','last','later','learn','leg','let','life','light','listen','little','live','long','love','make','man','meal','milk','miss','money','more','mountain','mouth','move','much','music','name','night','nose','now','number','often','open','outside','page','park','part','pay','place','plant','play','point','put','rain','read','right','road','room','run','school','see','set','short','sister','sit','sky','sleep','slow','small','soft','start','stop','story','study','sun','swim','table','take','talk','town','tree','turn','use','village','walk','watch','water','way','well','win','window','woman','word','write','year'],
  A2: ['able','accept','across','active','activity','actually','adult','advice','afternoon','age','agree','airport','almost','alone','along','although','amount','angry','animal','another','answer','appear','area','around','arrive','ask','attack','autumn','available','awful','balance','beautiful','become','before','behind','belong','below','benefit','best','better','body','both','bottom','bring','brother','business','call','camp','cause','centre','chance','change','character','charge','check','climb','close','clothes','club','collect','colour','comfort','common','community','compare','condition','confident','connect','continue','cross','decide','deep','deliver','depend','describe','detail','different','direction','dirty','discuss','divide','dress','during','early','earn','easy','either','empty','enjoy','enough','enter','especially','even','evening','event','every','everyone','example','except','exercise','explain','explore','extra','fail','familiar','famous','fast','final','follow','force','forward','free','fresh','front','full','future','glad','goal','good','grow','guess','guide','happen','happy','hard','hear','herself','himself','hold','holiday','hope','hour','hurt','image','include','individual','inside','instead','interest','issue','join','kind','knock','land','late','lead','leave','level','lift','likely','line','list','look','loud','lucky','machine','main','manage','map','mark','maybe','mean','meet','message','middle','mine','minute','modern','mother','must','near','need','new','next','nice','north','nothing','notice','offer','often','old','once','only','opinion','opposite','order','other','out','over','own','pass','past','people','perhaps','person','phone','pick','please','plus','popular','position','possible','practice','problem','process','programme','project','put','quite','reach','ready','real','reason','receive','recent','record','remember','repeat','reply','rest','result','return','rich','safe','same','save','second','seem','send','shape','share','show','sign','similar','since','situation','size','skill','smile','social','some','soon','sorry','south','speak','spend','sport','stay','step','still','street','strong','subject','sure','system','theme','themselves','tired','together','touch','trouble','true','try','under','view','voice','want','warm','week','while','whole','wide','without','worry','worth','young'],
  B1: ['abandon','abroad','absence','absolute','access','accurate','acquire','adjust','affect','agency','alike','allow','alongside','alternative','analyse','announce','anxious','appropriate','approve','aspect','assess','assist','associate','attitude','attract','aware','award','basis','border','capable','capture','career','carry','category','challenge','channel','chart','circumstances','cite','claim','clarify','classic','comfortable','comment','commit','communicate','complex','concentrate','conclude','consequence','considerable','consist','context','contrast','contribute','convention','convince','correspond','creative','critical','currently','damage','deadline','declaration','define','demonstrate','deny','determined','difficulty','diplomatic','document','dominant','efficient','eliminate','emotional','emphasis','enable','encourage','engage','evaluate','evidence','evident','exceed','exclude','explicit','expose','extensive','factor','failure','feature','focus','formal','fundamental','generate','global','gradually','grant','guarantee','handle','identify','impact','indicate','influence','informal','initially','innovative','inspire','integrate','intense','intention','investigate','justify','key','launch','lead','link','major','material','mechanism','motivate','negative','neutral','obtain','obvious','occur','oppose','option','overcome','participate','perspective','potential','predict','prefer','previous','principle','priority','profession','prohibit','promote','propose','protection','prove','pursue','raise','react','recognize','reform','region','regulate','reject','relate','reliable','represent','role','seek','select','separate','significant','solve','specific','statement','status','strategy','structure','submit','succeed','survey','task','threat','unique','update','various','version','vital'],
  B2: ['absorb','accomplish','accumulate','acknowledge','adequate','advocate','allocate','ambition','anticipate','apparent','arbitrary','assert','attribute','authority','autonomy','boost','catalyst','collaborate','competent','compile','compose','compromise','concede','conduct','confront','consensus','constraint','coordinate','cultivate','dedicate','deliberate','designate','devote','diminish','distinction','distribute','diverse','dynamic','elaborate','emerge','emphasise','ensure','exclude','facilitate','implement','imply','incentive','incorporate','initiate','interpret','maximize','minimize','monitor','negotiate','objective','perceive','persist','phase','precede','preliminary','prioritise','proportion','prospect','refine','reinforce','remedy','restrict','retain','revenue','revise','scope','specify','stabilise','subsequent','substantial','supplement','sustain','tolerate','transition','undergo','utilise','validate','verify','whereas'],
  C1: ['abstain','alleviate','ambivalent','articulate','astute','augment','brevity','circumvent','clandestine','coerce','concur','conjecture','consolidate','contemplate','contend','curtail','daunting','debilitating','defer','delve','deplete','discern','disseminate','eloquent','exacerbate','exemplify','expedite','explicit','formidable','foster','gauge','harbour','impede','inaugurate','incline','induce','inhibit','innate','invoke','juxtapose','lucid','meticulous','mitigate','nuance','obscure','perpetuate','plausible','postulate','pragmatic','precipitate','predominant','proliferate','prompt','rational','reconcile','scrutinise','sparse','speculate','substantiate','supersede','suppress','tangible','transcend','undermine','unprecedented','vague','yield'],
};

Object.entries(OXFORD).forEach(([level, words]) => {
  const missing = words.filter(w => !have.has(w));
  if (missing.length > 0) {
    console.log(`\n${level} missing (${missing.length}):`);
    missing.forEach(w => console.log(`  ${w}`));
  }
});

console.log('\nTotal words in dictionary:', W.length);
